definitions:
  controller.StudentInput:
    properties:
      age:
        type: integer
      class:
        type: integer
      name:
        type: string
    type: object
  models.Student:
    properties:
      age:
        type: integer
      class_id:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /student/{id}:
    patch:
      description: Update Student by id.
      parameters:
      - description: Student id
        in: path
        name: id
        required: true
        type: string
      - description: the body to update student
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controller.StudentInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Update Student.
      tags:
      - Student
  /students:
    get:
      description: Get a list of Student.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Student'
            type: array
      summary: Get all Student.
      tags:
      - Student
    post:
      description: Creating a new Student.
      parameters:
      - description: the body to create a new Student
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controller.StudentInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Create New Student.
      tags:
      - Student
  /students/{id}:
    delete:
      description: Delete a Student by id.
      parameters:
      - description: Student id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Delete one Student.
      tags:
      - Student
  /students/id/{id}:
    get:
      description: Get an Student by id.
      parameters:
      - description: Student id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Get Student.
      tags:
      - Student
  /students/name/{name}:
    get:
      description: Get an id by nama Student.
      parameters:
      - description: Student Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Get Id.
      tags:
      - Student
swagger: "2.0"
