definitions:
  controller.TugasPendahuluanInput:
    properties:
      deadline:
        type: string
      deskripsi:
        type: string
      judul:
        type: string
      kategori:
        type: string
      subJudul:
        type: string
    type: object
  models.TugasPendahuluan:
    properties:
      createdAt:
        type: string
      deadline:
        type: string
      deskripsi:
        type: string
      id:
        type: integer
      judul:
        type: string
      kategori:
        type: string
      subJudul:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /tugaspendahuluans:
    get:
      description: Get a list of TugasPendahuluan.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TugasPendahuluan'
            type: array
      summary: Get all TugasPendahuluan.
      tags:
      - TugasPendahuluan
    post:
      description: Creating a new TugasPendahuluan.
      parameters:
      - description: the body to create a new TugasPendahuluan
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controller.TugasPendahuluanInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TugasPendahuluan'
      summary: Create New TugasPendahuluan.
      tags:
      - TugasPendahuluan
  /tugaspendahuluans/{id}:
    delete:
      description: Delete a TugasPendahuluan by id.
      parameters:
      - description: TugasPendahuluan id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Delete one TugasPendahuluan.
      tags:
      - TugasPendahuluan
    patch:
      description: Update TugasPendahuluan by id.
      parameters:
      - description: TugasPendahuluan id
        in: path
        name: id
        required: true
        type: string
      - description: the body to update TugasPendahuluan
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controller.TugasPendahuluanInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TugasPendahuluan'
      summary: Update TugasPendahuluan.
      tags:
      - TugasPendahuluan
  /tugaspendahuluans/id/{id}:
    get:
      description: Get an TugasPendahuluan by id.
      parameters:
      - description: TugasPendahuluan id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TugasPendahuluan'
      summary: Get TugasPendahuluan.
      tags:
      - TugasPendahuluan
swagger: "2.0"
